dist: xenial
sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
env:
  - NETWORKX_VERSION=1.*
  - NETWORKX_VERSION=2.*
install:
  - pip install networkx==$NETWORKX_VERSION
  - pip install .
  - python setup.py sdist bdist_wheel
script:
  - py.test
deploy:
  - provider: pypi
    user: __token__
    password: $pypi_password
    on:
      python: "3.7"
      condition: $NETWORKX_VERSION = 2.*
      repo: dhimmel/obonet
      tags: true
      distributions: sdist bdist_wheel
